//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopperBackend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HopperEntities : DbContext
    {
        public HopperEntities()
            : base("name=HopperEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActiveRequest> ActiveRequests { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<HistoricalRequest> HistoricalRequests { get; set; }
        public virtual DbSet<Rider> Riders { get; set; }
        public virtual DbSet<RiderReview> RiderReviews { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<todoitem> todoitems { get; set; }
    }
}
