//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheHopperService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HopperEntities : DbContext
    {
        public HopperEntities()
            : base("name=HopperEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Driver> Drivers { get; set; }

        public System.Data.Entity.DbSet<TheHopperService.Models.ActiveRequest> ActiveRequests { get; set; }

        public System.Data.Entity.DbSet<TheHopperService.Models.HistoricalRequest> HistoricalRequests { get; set; }

        public System.Data.Entity.DbSet<TheHopperService.Models.Rider> Riders { get; set; }

        public System.Data.Entity.DbSet<TheHopperService.Models.RiderReview> RiderReviews { get; set; }
    }
}
